services:

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432" 
    volumes:
      - postgres-db:/var/lib/postgresql/data  

volumes:
  postgres-db: {}